#!/usr/bin/env python

import os, numpy as np
import pydoop.hdfs as hdfs
from bl.core.messages.Array import msg_to_Array

THIS_DIR = os.path.dirname(os.path.abspath(__file__))

INPUT = "file:%s/input" % THIS_DIR
OUTPUT = "file:%s/output.msg" % THIS_DIR
SCRIPT = "%s/../scripts/kinship" % THIS_DIR
EXPECTED_OUTPUT = "%s/expected_output.msg" % THIS_DIR
OPTS = "-m 5 -r 2 --log-level DEBUG --local-libhdfs-opts=-Xmx512m --mr-libhdfs-opts=-Xmx128m"

os.system("hadoop dfsadmin -safemode wait")
os.system("%s %s %s %s" % (SCRIPT, OPTS, INPUT, OUTPUT))

with hdfs.open(OUTPUT) as f:
  k = msg_to_Array(f.read())
with open(EXPECTED_OUTPUT) as f:
  exp_k = msg_to_Array(f.read())
np.allclose(k, exp_k)

print "OK."

# Local Variables: **
# mode: python **
# End: **
