#!/usr/bin/env python

import os, cPickle
import numpy as np
os.environ["LIBHDFS_OPTS"] = "-Xmx512m"

import pydoop
import pydoop.hdfs as hdfs
import bl.core.gt.kinship as kinship


THIS_DIR = os.path.dirname(os.path.abspath(__file__))

INPUT = "file:%s/input" % THIS_DIR
OUTPUT = "file:%s/output" % THIS_DIR
SCRIPT = "%s/../scripts/kinship" % THIS_DIR
EXPECTED_OUTPUT = "%s/expected_output.pickle" % THIS_DIR
OPTS = "-m 5 --log-level DEBUG --mr-libhdfs-opts=-Xmx128m"

os.system("%s dfsadmin -safemode wait" % pydoop.hadoop_exec())
try:
  hdfs.rmr(OUTPUT)
except IOError:
  pass
os.system("%s %s %s %s" % (SCRIPT, OPTS, INPUT, OUTPUT))

with hdfs.open(OUTPUT) as f:
  k = kinship.KinshipBuilder.deserialize(f.read())
with open(EXPECTED_OUTPUT) as f:
  exp_k = cPickle.load(f)
print "OK" if np.allclose(k, exp_k) else "ERROR"
