#!/usr/bin/env python

import sys
from bl.mr.seq.fasta2tab import run_task


def main(argv):
  run_task()


if __name__ == "__main__":
  main(sys.argv)


# Local Variables: **
# mode: python **
# End: **
