# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Array.proto',
  package='core_messages',
  serialized_pb='\n\x0b\x41rray.proto\x12\rcore_messages\"]\n\x05\x41rray\x12\x11\n\ttype_name\x18\x01 \x02(\t\x12\x12\n\nbyte_order\x18\x02 \x02(\t\x12\x0c\n\x04\x64ims\x18\x03 \x02(\x05\x12\x11\n\x05shape\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x0c\n\x04\x64\x61ta\x18\x05 \x02(\x0c')




_ARRAY = descriptor.Descriptor(
  name='Array',
  full_name='core_messages.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type_name', full_name='core_messages.Array.type_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='byte_order', full_name='core_messages.Array.byte_order', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dims', full_name='core_messages.Array.dims', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shape', full_name='core_messages.Array.shape', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    descriptor.FieldDescriptor(
      name='data', full_name='core_messages.Array.data', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['Array'] = _ARRAY

class Array(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARRAY
  
  # @@protoc_insertion_point(class_scope:core_messages.Array)

# @@protoc_insertion_point(module_scope)
