# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Dummy.proto',
  package='core_messages',
  serialized_pb='\n\x0b\x44ummy.proto\x12\rcore_messages\"9\n\x05\x44ummy\x12\x10\n\x08\x61_string\x18\x01 \x02(\t\x12\r\n\x05\x61_int\x18\x02 \x02(\x05\x12\x0f\n\x07\x61_float\x18\x03 \x02(\x02')




_DUMMY = descriptor.Descriptor(
  name='Dummy',
  full_name='core_messages.Dummy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a_string', full_name='core_messages.Dummy.a_string', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='a_int', full_name='core_messages.Dummy.a_int', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='a_float', full_name='core_messages.Dummy.a_float', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['Dummy'] = _DUMMY

class Dummy(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DUMMY
  
  # @@protoc_insertion_point(class_scope:core_messages.Dummy)

# @@protoc_insertion_point(module_scope)
