# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='MessageStreamHeader.proto',
  package='core_messages',
  serialized_pb='\n\x19MessageStreamHeader.proto\x12\rcore_messages\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"A\n\x13MessageStreamHeader\x12*\n\tkey_value\x18\x01 \x03(\x0b\x32\x17.core_messages.KeyValue')




_KEYVALUE = descriptor.Descriptor(
  name='KeyValue',
  full_name='core_messages.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='core_messages.KeyValue.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='core_messages.KeyValue.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=82,
)


_MESSAGESTREAMHEADER = descriptor.Descriptor(
  name='MessageStreamHeader',
  full_name='core_messages.MessageStreamHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key_value', full_name='core_messages.MessageStreamHeader.key_value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=149,
)

_MESSAGESTREAMHEADER.fields_by_name['key_value'].message_type = _KEYVALUE
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['MessageStreamHeader'] = _MESSAGESTREAMHEADER

class KeyValue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYVALUE
  
  # @@protoc_insertion_point(class_scope:core_messages.KeyValue)

class MessageStreamHeader(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGESTREAMHEADER
  
  # @@protoc_insertion_point(class_scope:core_messages.MessageStreamHeader)

# @@protoc_insertion_point(module_scope)
