#!/usr/bin/env python

# BEGIN_COPYRIGHT
# 
# Copyright (C) 2009-2013 CRS4.
# 
# This file is part of biodoop-core.
# 
# biodoop-core is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
# 
# biodoop-core is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
# 
# You should have received a copy of the GNU General Public License along with
# biodoop-core.  If not, see <http://www.gnu.org/licenses/>.
# 
# END_COPYRIGHT

"""
Dump a serialized kinship matrix to a text file.

FIXME: this is just a rough version
"""

import sys
import bl.core.gt.kinship as kinship


INPUT = sys.argv[1]
try:
  FO = open(sys.argv[2], "w")
except IndexError:
  FO = sys.stderr

with open(INPUT) as fi:
  k = kinship.KinshipBuilder.deserialize(fi.read())
  for row in k:
    FO.write(" ".join("% 14.7f" % x for x in row)+"\n")
