#!/usr/bin/env python

# BEGIN_COPYRIGHT
# END_COPYRIGHT

import sys, os
try:
  sys.path.remove(os.getcwd())
except ValueError:
  pass
from bl.core.app.kinship import main

if __name__ == "__main__":
  main(sys.argv)


# Local Variables: **
# mode: python **
# End: **
