#!/usr/bin/env python

"""
Local (i.e., no MapReduce) kinship matrix computation.

FIXME: this is just a rough version
"""

import sys, os
import bl.core.gt.kinship as kinship


INPUT = sys.argv[1]


def calc_kinship(input_fn):
  AlleleCountError = kinship.AlleleCountError
  builder = None
  with open(input_fn) as fi:
    for i, line in enumerate(fi):
      line = line.split()
      if builder is None:
        builder = kinship.KinshipBuilder(len(line))
      try:
        builder.add_contribution(line)
      except AlleleCountError as e:
        raise RuntimeError("line %d: %s" % (i+1, e))
  return builder.build()


if __name__ == "__main__":
  k = calc_kinship(INPUT)
  tag = os.path.splitext(os.path.basename(INPUT))[0]
  with open("%s.kinship" % tag, "w") as fo:
    fo.write(kinship.KinshipBuilder.serialize(k))
